### ISSUE TITLE
values must be atoms or strings

### ISSUE THREAD

**Issue by AnnieAtDataChemist** [terminusdb/terminus_store_prolog#12]
people will want to store ints and floats and such

**Comment by matko** [comment]
Right now ints and floats and such are stored as strings, yes. This is how HDT does it to, and it is how it is when you got an rdf file in ttl format or somesuch as well.

But we definitely want to be able to store numerical types directly. This is not an oversight, we just didn't get to implementing it yet!

**Comment by AnnieAtDataChemist** [comment]
Which is why I bugged it!  Now we have a record.

**Comment by matko** [comment]
Having proper types in the store is on the roadmap. This ticket is no longer needed for keeping track of that.
