### ISSUE TITLE
calling open_write more than once workflow is baffling

### ISSUE THREAD

**Issue by AnnieAtDataChemist** [terminusdb/terminus_store_prolog#13]
The current scheme with builder and layer and getting a builder is pretty confusing. Perhaps head should be guaranteed to return some layer or something - the open_write the first time on the graph, and from then on on the layer was baffling.

**Comment by matko** [comment]
What I want is for `open_write` to work on a named graph even if it has no head yet. Then that can be the 'symmetric' part of the api where it just always works.

A named graph that has no layer should imo not be returning a layer on head just to make parts of the api happy, cause it'd be a bold-faced lie.
