### ISSUE TITLE
terminus_store:subject_predicate_lookup_object/2 leaves choice point.

### ISSUE THREAD

**Issue by AnnieAtDataChemist** [terminusdb/terminus_store_prolog#16]
1. run the terminus_store_test

```
swipl run_test.pl -- -n 1 
?- tspy(opt_test).
?-go.
```
Graphic debugger will stop at opt_test(one_big_union_er_layer)

s to step over

EXPECTED: last item on stack is opt_test
OBSERVED: 10_000 choice points for terminus_store:subject_predicate_lookup_object/2

**Comment by matko** [comment]
`subject_predicate_lookup_object/2` is actually nondet so I am not surprised that it leaves a choice point.
This predicate takes a subject_predicate_lookup blob in its first argument, then fills the second argument (the object) with the object of the first matching triple, leaving a choice point for the second match, etc.

If there's unwanted choice points, the fault lies not with `subject_predicate_lookup_object/2` but with its caller, which should clean up those choice points if it is not interested in further matches.

**Comment by AnnieAtDataChemist** [comment]
Yup, turns out it's the test harness that wasn't trimming. My bad.
