### ISSUE TITLE
Pack cannot be installed in Ubuntu 18

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminus_store_prolog#3]
Trying to install the pack (using the `pack_install(terminus_store_prolog)` query on Ubuntu 18.04.3 using `cargo` and `rustc` 1.36.0 fails with the compilation error:

```
%    Compiling terminus-store v0.7.6
ERROR: error: enum variants on type aliases are experimental
ERROR:    --> /home/pmoura/.cargo/registry/src/github.com-1ecc6299db9ec823/terminus-store-0.7.6/src/layer/layer.rs:459:13
ERROR:     |
ERROR: 459 |             Self::Unresolved(_) => false,
ERROR:     |             ^^^^^^^^^^^^^^^^^^^
```

**Comment by rrooij** [comment]
Hey @pmoura, unfortunately the Ubuntu repos lack behind the real Rust stable. I'd recommend to install Rust stable with rustup. The minimal supported version is 1.37.0

This should be written somewhere by the way.

**Comment by pmoura** [comment]
I would suggest mentioning the minimal Rust version required in the readme file.

In order to update, I first removed the previous installations of `cargo` and `rustc`:

```
$ sudo apt remove cargo
$ sudo apt remove rustc
```

After:

```
$ sudo apt update
$ sudo apt upgrade
$ curl https://sh.rustup.rs -sSf | sh
```

The failed attempt to install the pack leaves files that should be removed first:

```
$ swipl
?- pack_remove(terminus_store_prolog).
...

?- pack_install(terminus_store_prolog).
...
```

After these steps, pack installation was successful.
