### ISSUE TITLE
Pack cannot be installed on macOS

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminus_store_prolog#4]
Trying to install the pack in macOS (running SWI-Prolog 8.1.16) fails with the error:

```
%    Compiling tokio-uds v0.2.5
%    Compiling tokio v0.1.22
%    Compiling terminus-store v0.7.6
%    Compiling terminus-store-prolog v0.1.0 (/Users/pmoura/.local/share/swi-prolog/pack/terminus_store_prolog/rust)
%     Finished release [optimized] target(s) in 1m 08s
% cp rust/target/release//libterminus_store_prolog.so  lib/x86_64-darwin
% cp: rust/target/release//libterminus_store_prolog.so: No such file or directory
% make: *** [build] Error 1
```

The error results from the Rust compilation generates a `.dylib` file instead of a `.so` file:

```
$ ll /Users/pmoura/.local/share/swi-prolog/pack/terminus_store_prolog/rust/target/release/
total 5904
drwxr-xr-x   22 pmoura  staff      704 Nov 22 15:10 build
drwxr-xr-x  160 pmoura  staff     5120 Nov 22 15:11 deps
drwxr-xr-x    2 pmoura  staff       64 Nov 22 15:10 examples
drwxr-xr-x    2 pmoura  staff       64 Nov 22 15:10 incremental
-rw-r--r--    1 pmoura  staff      198 Nov 22 15:11 libterminus_store_prolog.d
-rwxr-xr-x    2 pmoura  staff  3017552 Nov 22 15:11 libterminus_store_prolog.dylib
drwxr-xr-x    2 pmoura  staff       64 Nov 22 15:10 native
```

The `.so` extension is specified in the `Makefile:

```
$ cat /Users/pmoura/.local/share/swi-prolog/pack/terminus_store_prolog/Makefile 
RUST_LIB_NAME = terminus_store_prolog
RUST_LIB = lib$(RUST_LIB_NAME).$(SOEXT)
RUST_TARGET=release
RUST_TARGET_DIR = rust/target/$(RUST_TARGET)/
SOEXT = so 
```

But the `SOEXT` value is taken from the `buildenv.sh` file generated by the query `prolog_pack:save_build_environment('./')`. I don't know why SWI-Prolog is setting the extension to `.so` in macOS where the default for shared libraries is `.dylib`. Thus, it's not clear where this issue should be fixed.

**Comment by pmoura** [comment]
Patching the `make` and `Makefile` files to use the `.dylib` extension solves the error above but then we get linker errors:

```
   Compiling terminus-store v0.7.6
   Compiling terminus-store-prolog v0.1.0 (/Users/pmoura/.local/share/swi-prolog/pack/terminus_store_prolog/rust)
    Finished release [optimized] target(s) in 56.04s
cp rust/target/release//libterminus_store_prolog.dylib lib/x86_64-darwin
gcc -shared -fPIC -pthread -I"/Users/pmoura/lib/swipl/include" -Wall -o lib/x86_64-darwin/libterminus_store.dylib ./c/*.c -Isrc -L./lib/x86_64-darwin -Wl,-rpath /Users/pmoura/.local/share/swi-prolog/pack/terminus_store_prolog/lib/x86_64-darwin -lterminus_store_prolog
Undefined symbols for architecture x86_64:
  "_PL_blob_data", referenced from:
      _release_store_blob in blobs-f1a0e7.o
      _release_named_graph_blob in blobs-f1a0e7.o
      _release_layer_blob in blobs-f1a0e7.o
      _release_layer_builder_blob in blobs-f1a0e7.o
      _release_subject_lookup_blob in blobs-f1a0e7.o
      _release_subject_predicate_lookup_blob in blobs-f1a0e7.o
      _release_predicate_lookup_blob in blobs-f1a0e7.o
      ...
  "_PL_close_foreign_frame", referenced from:
      _pl_object_lookup_subject_predicate in terminus_store-5f51f0.o
...
```

**Comment by matko** [comment]
I see in your other issue that you managed to get a working build in the end. Was that on osx?

Are you able to install other packs that have a native compilation step? For example, are you able to install the hdt pack?

**Comment by pmoura** [comment]
I'm currently trying to get a working setup on Ubuntu 18.04.3. No progress on macOS. Still debugging installation of the `hdt` pack (on Ubuntu):

```logtalk
?- pack_install('https://github.com/GavinMendelGleason/hdt.git').
% Cloning into '/home/pmoura/.local/share/swi-prolog/pack/hdt'...
Verify package status (anonymously)
	at "https://www.swi-prolog.org/pack/query" Y/n? 
% Contacting server at https://www.swi-prolog.org/pack/query ...
ERROR: Server reported the following error:
ERROR: No permission to register pack(hdt) `'https://github.com/GavinMendelGleason/hdt.git''
Package:                hdt
Title:                  Access RDF HDT files
Installed version:      0.5
Author:                 Jan Wielemaker <J.Wielemaker@vu.nl>
Maintainer:             Jan Wielemaker <J.Wielemaker@vu.nl>
Packager:               Jan Wielemaker <J.Wielemaker@vu.nl>
Home page:              https://github.com/GavinMendelGleason/hdt
Download URL:           https://github.com/GavinMendelGleason/hdt.git
Run post installation scripts for pack "hdt" Y/n? 
% git submodule update --init
% Submodule 'hdt-cpp' (https://github.com/rdfhdt/hdt-cpp.git) registered for path 'hdt-cpp'
% Cloning into '/home/pmoura/.local/share/swi-prolog/pack/hdt/hdt-cpp'...
% Submodule path 'hdt-cpp': checked out 'a8aafe32e0209a50a7671ddd5376b5c0d6934496'
% cd hdt-cpp && ./autogen.sh
ERROR: configure.ac:10: error: possibly undefined macro: AC_SUBST
%       If this token and others are legitimate, please use m4_pattern_allow.
%       See the Autoconf documentation.
ERROR: configure.ac:48: error: possibly undefined macro: AC_DEFINE
% autoreconf: /usr/bin/autoconf failed with exit status: 1
% Makefile:22: recipe for target 'hdt-cpp/libhdt/.make-senitel' failed
% make: *** [hdt-cpp/libhdt/.make-senitel] Error 1
ERROR: Process "process(path(make),[all])": exit status: 2
ERROR: In:
ERROR:   [20] throw(error(process_error(...,...),_1954))
ERROR:   [18] '$apply':forall(prolog_pack:member(all,...),prolog_pack:run_process(...,...,...)) at /usr/lib/swi-prolog/boot/apply.pl:52
ERROR:   [14] prolog_pack:pack_post_install(hdt,'/home/pmoura/.local/share/swi-prolog/pack/hdt',[git(true),...|...]) at /usr/lib/swi-prolog/library/prolog_pack.pl:1017
ERROR:    [9] <user>
ERROR: 
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
```

**Comment by pmoura** [comment]
The errors above when installing the `hdt` pack were due to a missing dependency. Btw, in the `BUILD.md` file in the `master` branch, it would be preferable to instruct to install `hdt-cpp` **before** installing the `hdt` pack to avoid these errors.

**Comment by matko** [comment]
Makefile contained a definition for SOEXT, setting it to 'so' unconditionally. The latest commit removes that.

Are you able to install the pack now?

**Comment by pmoura** [comment]
I noticed that. In the `clean` target, there's also a hard-coded `.so` extension that should be changed to `.$(SOEXT)`. But, as I mentioned above, that doesn't solve the problem as the SWI-Prolog `prolog_pack:save_build_environment('./')` predicate, that is used to generate the `buildenv.sh` source'd during compilation is setting the extension to `.so`. From the installation of SWI-Prolog itself on macOS, both `.so` files and `.dylib` files are generated and used without trouble. Thus, fixing this issue may requite just to find the correct linker incantation that avoids the `Undefined symbols for architecture x86_64` errors above. I will take another look to it tomorrow.

**Comment by dnknth** [comment]
Here my Makefile that gets TerminusDB up and running. Sorry, I did not bother with the Linux and Windows rules, so it is just a quick hack for `x86_64-darwin`.  Hope you can use some of it (rename to Makefile for testing)

[Makefile.txt](https://github.com/terminusdb/terminus_store_prolog/files/5044173/Makefile.txt)

Requirements via [Homebrew](https://brew.sh) (not included in the Makefile):
 * `swi-prolog`
 * `rust`

**Comment by dnknth** [comment]
Oh, I forget to mention that this has been only tested by running `./make` manually in the pack directory.
I am not familiar with the environment variables that SWI passes to the `make` run in `pack_install/1`, so it will likely need some tuning.

Just a rough first cut.

**Comment by rrooij** [comment]
Seems like this should work now with the latest change from @dnknth

**Comment by rrooij** [comment]
You may be interested in the new build instructions I released on how to run TerminusDB itself on Mac OS.

https://github.com/terminusdb/terminusdb-server/blob/dev/docs/BUILD.md#mac-os

You may have figured this out yourself already. :smile:
