### ISSUE TITLE
Non-necessary use proprietary compound term with zero arguments in clause head?

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminus_store_prolog#6]
In the definition of the following predicate:

https://github.com/terminusdb/terminus_store_prolog/blob/98599a97b6df50e06f998b68634684d9c7250d91/prolog/terminus_store.pl#L416

is there any reason to use a proprietary compound term with zero arguments in clause head instead of an atom? All calls to this predicate don't seem to require it.

Found this issue while debugging some odd exceptions that occur with SWI-Prolog 8.0.3 but not with 8.1.16, which suggests that clause head is triggering a SWI-Prolog bug in the stable version that's already fixed in the current devel version.

**Comment by rrooij** [comment]
Thanks for spotting this! It was a typo. I'm way too used to C-like languages.

https://github.com/terminusdb/terminus_store_prolog/commit/b6f077aa0fcbdc2386f398fc07b64213223e08d5
