### ISSUE TITLE
open_directory_store when directory does not exist

### ISSUE THREAD

**Issue by Anniepoo** [terminusdb/terminus_store_prolog#9]
We should check for directory existance when opening the store.

On a machine WITHOUT a /tmp/demo directory:

Welcome to SWI-Prolog (threaded, 64 bits, version 8.0.3)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- open_directory_store('/tmp/demo', Store).
Store = <store_blob> .

?- open_write($Store, Builder).
ERROR: Unhandled exception: terminus_store_rust_error('No such file or directory (os error 2)')

EXPECTED: throw exception from open_directory_store/2
OBSERVED: lazily only flips when the store's written

**Comment by spl** [comment]
See #45.
